### ISSUE TITLE
Command 'ZREMRANGEBYLEX' is not a registered Redis command

### ISSUE THREAD

**Issue by abraovic** [nrk/predis#303]
Hi @nrk,

I have problem with ZREMRANGEBYLEX command. Here is my code:
```
$redis->zremrangebylex($key, $min, $max);
```
and I get
```
Predis\ClientException: Command 'ZREMRANGEBYLEX' is not a registered Redis command.

..../symfony/vendor/predis/predis/src/Profile/RedisProfile.php:88
..../symfony/vendor/predis/predis/src/Client.php:318
..../symfony/vendor/predis/predis/src/Client.php:309
```

Redis version 3.0.6
PHP version  5.5.30
Predis version 1.0.3

Can you help me with this?

Thanks,
Ante.

Update:
It's same for ZRANGEBYLEX

**Comment by abraovic** [comment]
Resolved. 

It was not due to Predis lib. It was due to snc_redis bundle for symfony2. For some reason in its options default version is 2.4 instead of default. So basically you need to put it manually to required version.

```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn:
                - redis://localhost
            options:
                profile: 3.0
```
